#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/bunny/RoboDogFetch/devel_isolated/rtabmap_viz:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_slam:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_odom:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_legacy:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_util:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_sync:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_rviz_plugins:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_ros:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_python:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_examples:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_demos:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_conversions:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_msgs:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_launch:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_costmap_plugins:/home/bunny/RoboDogFetch/devel_isolated/robot_control:/home/bunny/RoboDogFetch/devel_isolated/path_planning:/home/bunny/RoboDogFetch/devel_isolated/object_detection:/home/bunny/RoboDogFetch/devel_isolated/input_camera:/home/bunny/RoboDogFetch/devel:/opt/ros/noetic:/home/bunny/RoboDogFetch/devel_isolated/rtabmap'
export LD_LIBRARY_PATH='/home/bunny/RoboDogFetch/devel_isolated/rtabmap_slam/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_odom/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_legacy/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_util/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_sync/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_rviz_plugins/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_ros/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_python/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_examples/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_demos/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_conversions/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_msgs/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_launch/lib:/home/bunny/RoboDogFetch/devel_isolated/rtabmap_costmap_plugins/lib:/home/bunny/RoboDogFetch/devel_isolated/robot_control/lib:/home/bunny/RoboDogFetch/devel_isolated/path_planning/lib:/home/bunny/RoboDogFetch/devel_isolated/object_detection/lib:/home/bunny/RoboDogFetch/devel_isolated/input_camera/lib:/home/bunny/RoboDogFetch/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/bunny/RoboDogFetch/devel_isolated/rtabmap/lib:/usr/local/lib'
export PATH='/opt/ros/noetic/bin:/home/bunny/RoboDogFetch/devel_isolated/rtabmap/bin:/home/bunny/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export ROSLISP_PACKAGE_DIRECTORIES="/home/bunny/RoboDogFetch/devel_isolated/rtabmap_viz/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/bunny/RoboDogFetch/src/rtabmap_ros/rtabmap_viz:$ROS_PACKAGE_PATH"